### ISSUE TITLE
Access to REST api blocked by CORS policy

### ISSUE THREAD

**Issue by 6xtvo** [Ascendus/MatrixWebsite#18]
```
Access to fetch at 'https://matrixdev.xyz/api/v1/oauth/details' from origin 'https://www.matrixdev.xyz' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.

Failed to load resource: net::ERR_FAILED
www.matrixdev.xyz/:1 Access to fetch at 'https://matrixdev.xyz/api/v1/get/server/755687537753718815' from origin 'https://www.matrixdev.xyz' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.

matrixdev.xyz/api/v1/get/server/755687537753718815:1 Failed to load resource: net::ERR_FAILED
```
REST api is still being unable to be fetched, so incorrect statistics is being displayed.
Login system also does not display the user's username after they have logged in.

**Comment by Lucaslah** [comment]
I have a fix, it should work, but we should try and find where CORS is blocking the request.

**Comment by 6xtvo** [comment]
> I have a fix, it should work, but we should try and find where CORS is blocking the request.

I'm not too familiar with this stuff, so I'm afraid it's mostly up to you.

**Comment by Lucaslah** [comment]
Alright

**Comment by Lucaslah** [comment]
@Ascendus https://github.com/Ascendus/MatrixWebsite/pull/19#issuecomment-996455101
Just so I can see if the build works

**Comment by 6xtvo** [comment]
Alright, merging now.

**Comment by 6xtvo** [comment]
Hmm, nothing seems to have changed still.

**Comment by Lucaslah** [comment]
I don't get it, I've tried everything I can think of

**Comment by Lucaslah** [comment]
I can implementation a temp fix

**Comment by 6xtvo** [comment]
Sure.

**Comment by Lucaslah** [comment]
Basically if we change to URL to something other than `https://matrixdev.xyz/api` the CORS error should go away.

I'm going to try `https://stone.cssudii.tk/matrix/api`

This is because the error is `Cross-Origin Request Blocked: The Same Origin Policy` if we use a URL that is not on the same origin it should work.

**Comment by Lucaslah** [comment]
Not 100% on this, but its the only thing I can think of.

**Comment by 6xtvo** [comment]
Alright. Maybe we can ask around later for help on this.

**Comment by Lucaslah** [comment]
Alright, well I push the temp fix for now

**Comment by 6xtvo** [comment]
We still need to solve #21 and the username not appearing for some users.

**Comment by 6xtvo** [comment]
Maybe an issue is because you didn't compile the TypeScript code? When I pulled the code from the repo there was only TypeScript code.

**Comment by Lucaslah** [comment]
I recompile locally every time I restart it

**Comment by Lucaslah** [comment]
Anyway #23

**Comment by Lucaslah** [comment]
Dang, it did not work

**Comment by 6xtvo** [comment]
It seems that it's still throwing the same error.

**Comment by Lucaslah** [comment]
New Error: `Reason: Credential is not supported if the CORS header ‘Access-Control-Allow-Origin’ is ‘*’`

**Comment by 6xtvo** [comment]
![image](https://user-images.githubusercontent.com/72182515/146497697-70b4ae58-296a-448b-b0c3-ad1fa411a7b4.png)

**Comment by Lucaslah** [comment]
We could go back to `matrixwebsite.cssudii.tk`, that would fix it as it worked before

**Comment by 6xtvo** [comment]
I'm assuming it doesn't work when we put `credentials: "include"`.

> We could go back to `matrixwebsite.cssudii.tk`, that would fix it as I worked before

Yeah, I guess. Have fun changing all the domains. Last time with the domain we still had the login error where the username wouldn't appear, though.

**Comment by Lucaslah** [comment]
I could get it up at `api.matrixdev.xyz`

**Comment by 6xtvo** [comment]
Good idea.

**Comment by Lucaslah** [comment]
Just have to wait until feb 2022

**Comment by 6xtvo** [comment]
Yikes.

**Comment by Lucaslah** [comment]
Last try: #24

**Comment by Lucaslah** [comment]
Because I found that this issue is not a code issue and rather an issue with my proxy blocking the request, this will be fixed in February 2022 or possibly in late January, until then I will try to find a temporary solution to this issue.

**Comment by 6xtvo** [comment]
Waiting until Feburary 2022, issue no longer needs to be open until further development.
