### ISSUE TITLE
Seperate website and bot

### ISSUE THREAD

**Issue by 6xtvo** [Ascendus/MatrixWebsite#22]
It'll probably be a good idea to seperate the website and bot since they don't have to be together, plus every time a commit is pushed to the repository, it takes away a deployment from my Vercel account, so it wastes them unnecessarily.

I'll separate them locally, then create a new repository and project board for Matrix Bot, while this repository will remain for the website. (I won't do this yet, maybe sometime later when I feel like it.)

**Comment by Lucaslah** [comment]
Good idea

**Comment by Lucaslah** [comment]
I do think we should do this sooner as it will save deployment's

**Comment by 6xtvo** [comment]
Being completed now.
