### ISSUE TITLE
Exclude compiled JavaScript from repository

### ISSUE THREAD

**Issue by Lucaslah** [Ascendus/MatrixWebsite#25]
Reason: So there is no chance of using outdated code if you forget to rebuild the typescript, also so if I only edit a typescript file and don’t rebuild then push it and update and build on another computer I don’t have to run `git stash` before I can update again.

**Comment by 6xtvo** [comment]
Removed `dist` directory in https://github.com/Ascendus/MatrixWebsite/commit/899fc1b4c6d32ce08e7715b78fa5ad90a3837e0e, pulled changes to my local repository in https://github.com/Ascendus/MatrixWebsite/commit/5c9acf66f07e2b9f8bb8cac17794ffdb70790d3b and includes the `dist` directory in [`.gitignore`](https://github.com/Ascendus/MatrixWebsite/blob/main/.gitignore) in https://github.com/Ascendus/MatrixWebsite/commit/4fc893f30d3d9db9a411f0f467d30f341e9e9f58.
